dataset_path: DynaMath/DynaMath_Sample
dataset_kwargs:
  token: True
task: "dynamath_cot"
test_split: sample_variant1
output_type: generate_until
doc_to_visual: !function utils.dynamath_doc_to_visual
doc_to_text: !function utils.dynamath_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 2048
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.dynamath_gpt_eval_process_results
metric_list:
  - metric: dynamath_gpt_eval_score
    aggregation: !function utils.dynamath_aggregate_results_eval
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    prompt_format: solution
    mc_prompt: "First give the reasoning and then write your final answer in the format 'Answer: X' where X is the option's letter from the given choices."
    short_answer_prompt: "First give the reasoning and then write your final answer in the format 'Answer: X'."
dataset_kwargs:
  load_from_disk: true